### ISSUE TITLE
cannot find base url when using library for Data Studio Connector

### ISSUE THREAD

**Issue by grantkemp** [gsuitedevs/apps-script-oauth2#136]
I am trying to use this to create an open source data connector for Data Studio. 

The issue is that I can't seem to use this with a client_credentials based Oauth2 api. 

I get this error message: 
```
`Script error message: Authorization base URL is required.
 Script error cause: USER
 Script error stacktrace: 
  :45
  validate_:42
  :312
  get3PAuthorizationUrls:144`
```

Here is the code I am using to generate it: 
```
function getOAuthService() {
  return OAuth2.createService('searchMetrics')
  .setTokenUrl('http://api.searchmetrics.com/v3/token')
  .setGrantType('client_credentials')
    .setClientId('****removed****')
    .setClientSecret('*****removed*****')
    .setPropertyStore(PropertiesService.getUserProperties())
    .setCallbackFunction('authCallback')
};

function get3PAuthorizationUrls() {
  console.log(getAuth
  return getOAuthService().getAuthorizationUrl();
}
````
I am a bit confused - if you are using Client_creds mode for oauth2 - doesn't that mean that you don't need a Authorization base URL?

**Comment by erickoledadevrel** [comment]
Hmm, could be a bug. Can you show the service setup code you used?

**Comment by erickoledadevrel** [comment]
Ping.

**Comment by oshliaer** [comment]
I've wrote to searchmetrics.com for an access to the API.

**Comment by erickoledadevrel** [comment]
I see the problem now. You are calling `getAuthorizationUrl()` on the service which is triggering the error. Since you are using the `client_credentials` you don't need the user to visit an authorization URL. Simply delete the `get3PAuthorizationUrls()` method and it should remove the error. You'll also need to manually [set the Authorization header](https://github.com/gsuitedevs/apps-script-oauth2/blob/master/samples/TwitterAppOnly.gs#L49), since it isn't done for you automatically when you set a client ID and secret.
