### ISSUE TITLE
Avoid lock when token is still valid 

### ISSUE THREAD

**Issue by tdelmas** [gsuitedevs/apps-script-oauth2#143]
For performances reasons, it's better to avoid locks when possible.

- When the token is still valid, there is no need for a lock
- When the token need to be refreshed, the time spent to lock is negligible versus the http request.

So in `Service_.prototype.hasAccess`, before using `this.lockable_` I think it should check if there is an unexpired token, and is so, returns it without lock.

**Comment by erickoledadevrel** [comment]
So my original thought was that I wanted to prevent duplicate refreshes of the access token, and in order to do that you need to lock before you check to see if it's expired. If we only lock once we determine that it is expired, we end up with the following:

Execution #1 | Execution #2
------------ | -------------
Is token expired? Yes | ...
Acquire lock | ...
Start refreshing token | ...
... | Is token expired? Yes
... | Wait for lock
Refresh complete | ...
Release lock | ...
... | Acquire lock
... | Start refreshing token
... | Refresh complete
... | Release lock

To prevent the token from being refreshed twice, we need to lock before we check if it's expired, so that the second execution see's a non-expired token when it checks.

Now the original problem was due to the tokens getting saved out of order, such that the token from the first execution would be the one persisted in the properties, but it was invalidated by the token requested in the second execution. Locking after we check for expiration would result in two tokens, but I think it would guarantee that they are saved in the correct order.

Thoughts?

**Comment by tdelmas** [comment]
It will works but I think a better design would be to only request the token once. So if two concurrent thread request the token, one refresh it and both gains access to it.

I feel it's a better design because it avoid duplicate tokens and is faster because if one precess is already in the middle of the renewal, the second one will get the renewed token as soon as the first one gets it.

|  Execution 1 | Execution 2  |
|---|---|
|  Is token N expired? Yes |   |
| Acquire lock  |   |
| is current token N expired? Still Yes  |   |
|   |  Is token expired? Yes |
|   |  Wait for lock |
| Refresh complete : current token=N+1 |   |
|  Release lock |   |
|   | is current token N+1 expired? No  |
|   | Release lock  |
|   |   |

**Comment by tdelmas** [comment]
(of course, if there is **no** token, no lock should be done)

**Comment by erickoledadevrel** [comment]
I hadn't thought of that, but makes sense. I sent out PR #147 to implement this. Please take a look.
