### ISSUE TITLE
Forcing the sign in page to appear on popup screen

### ISSUE THREAD

**Issue by chinuhub** [gsuitedevs/apps-script-oauth2#170]
I have a google app script based web app where I am using this library to add google auth support. On the first login, an auth URL gets generated and passed to the event handler of the login button. When clicking this button I want to open sign in page on a popup and after authentication, the redirected URI should open up in the parent window. But every time when I click on the auth URL the google auth screen for consent opens up in a different tab. Is there a way to enforce opening popup for this behavior?

Thanks.

**Comment by erickoledadevrel** [comment]
I'm not entirely clear what the issue is, but it doesn't seem directly related to this library, as this library doesn't have any impact on how the auth URL is opened. 

In general the redirect URI is always going to open in whatever window / tab the auth prompt was opened in. You can create a redirect URI that closes the popup and send a message back to your web app, as is shown in the [webapp sample](https://github.com/gsuitedevs/apps-script-oauth2/blob/master/samples/WebApp/Callback.html).

**Comment by chinuhub** [comment]
Thanks a lot for the reference.
