### ISSUE TITLE
Script delayed (1.0 min) waiting for quota 

### ISSUE THREAD

**Issue by gyoshi02** [gsuitedevs/apps-script-oauth2#217]
Hello, 

Trying to use the GoogleServiceAccount.gs script, but tweaked it to find user email delegates. 
We are trying to create a report for when 1  of 7000 users might delegate their inbox. 
If I throw a list of 150 users, that I know already have an email delegate, the script works fine. 
However, if I try throwing 200 users, most of which don't have a delegate, I run  info script delays. 
It seems like its something with the Properties store.
The whole error message is:
Service invoked too many times for one day: graphite property writes. (line 125, file "Storage", project "OAuth2")
I read the section about "Caching" but wasn't sure if I should be using UserCache, or ScriptCache. 
I also wasn't sure if I required the "Locking" due to the amount of users I was trying to query. 
Thanks,

**Comment by erickoledadevrel** [comment]
Every time the OAuth flow completes it stores the token in the properties store, and optionally a cache. This is especially important for the user-based flow, since you need to store a refresh token to avoid constantly asking the user to re-approve after the access token expires.

For the service account flow there are no prompts or refresh tokens, so storing the token in the properties isn't as important. In your case you are generating so many tokens in such a short period that you are exceeding the quota for writing to the properties store. Adding a cache wouldn't help, since the problem is with writes and not reads.

I think a workaround would be to use a "fake" properties store that doesn't write to the properties along with a cache. The cache would allow you to reuse the access token and the fake properties service would ensure you don't hit the quota. You can copy a fake memory-backed PropertiesService from the OAuth1 library:

https://github.com/gsuitedevs/apps-script-oauth1/blob/master/src/MemoryProperties.gs

Use it in your service and let me know if that resolves the issue.

**Comment by gyoshi02** [comment]
Thanks for the quick response here.  
That makes a lot of sense, as I created another basic copy what i'm trying to accomplish with your script, and walked through the token store process, and reviewed all of the logs.  I thought It was an issue with data being removed from the script cache once it has a response, but wasn't able to tie back the proper logic to remove it. 
I'll have to try this later this evening, and provide an update.

**Comment by gyoshi02** [comment]
Hey, 
I'm still a relative newb here, and am not fully understanding where I'd need to incorporate this part of the code. I've created a new script file named MemoryProperties.gs, and copied the contents of MemoryProperties.gs.
However, i'm not sure what needs to be replaced in terms of the cache(properties store). 
![image](https://user-images.githubusercontent.com/45863342/75126311-32fc2c80-566e-11ea-8661-ac028cad8c0e.png)

**Comment by erickoledadevrel** [comment]
You're going to need to do this:

```
.setPropertiesStore(new MemoryProperties())
```

**Comment by gyoshi02** [comment]
Thank you for all your advice here. 
That worked perfectly.  I'm now able to query 1k users per script run without any errors.

**Comment by erickoledadevrel** [comment]
Great! I have sent out a PR that should allow this to work even without using `MemoryProperties`. Thanks for raising this issue.

**Comment by erickoledadevrel** [comment]
I just released version 36 of the library, which no longer requires a properties store to be set. Once you upgrade the version of the library you are using, simply omit the line `setPropertyStore` and it should work the same as using `MemoryProperties`.
