### ISSUE TITLE
Allow custom storage implementations

### ISSUE THREAD

**Issue by Blacksmoke16** [gsuitedevs/apps-script-oauth2#234]
I got an implementation based on #228 working, and things are going quite well.  However, some more advanced users are reaching the storage limits on `documentProperties` due to the amount of characters they are trying to authenticate.  

The cleanest solution I can think of is to store token/character data within the spreadsheet itself.  Currently the OAuth service already has an abstraction for this, as everything interfaces with a `Storage` object instead of directly with the properties/cache services.

Thoughts on adding a `setStorage(storageObject)` method to the service?  I'm thinking this would allow me/others to define custom classes to determine how/where auth data is persisted.

I'd be happy to make a PR if this is something that would be accepted.

**Comment by erickoledadevrel** [comment]
The solution you posted in #228 uses one property to store a map of all of the characters. If the quota limit is related to the maximum size of a single property, you could instead look towards breaking each character up into it's own property, and then using `Properties.getProperties()` to retrieve them all. That may be a short term solution that doesn't involve much new code.

While you could swap out the entire Storage class, you likely would still want to use the in-memory and CacheService-based caching it provides even if you do permanently store the data in the spreadsheet instead. I think a better approach, although still a bit janky, would be to create a custom Properties class that reads/writes to the spreadsheet, and hand that to the service instead of `DocumentProperties`. You can see an example of what's needed if a fake properties store here:

https://github.com/gsuitedevs/apps-script-oauth2/blob/master/test/mocks/properties.js

**Comment by Blacksmoke16** [comment]
> If the quota limit is related to the maximum size of a single property, you could instead look towards breaking each character up into it's own property, and then using `Properties.getProperties()` to retrieve them all.

I considered this, however I calculated the token in properties is ~4 kB, so given a 500 kB total storage limit, there would still be a hard cap of ~125 characters (which is apparently not enough for some people).

> While you could swap out the entire Storage class,

Yea, this is what I ended up doing (still a WIP): https://github.com/Blacksmoke16/GESI/blob/support-alt-storage-method/src/script/sheet_storage.ts

Unique ID and the refresh token are stored in the sheet.  Granted at and access token are stored in cacheService.  A sheet lookup is only made once,  takes ~1s to create an oauthService object, including the sheet lookup.

Then, because of JS, I can just directly override the `storage_` object. https://github.com/Blacksmoke16/GESI/blob/support-alt-storage-method/src/script/gesi.ts#L367.  Given this functionality is opt in, and specific to my usecase, I think it turned out fairly well.

**Comment by erickoledadevrel** [comment]
Thanks for sharing! Your implementation of `SheetStorage` always assumes the value is a token, which isn't accurate, but will work if you only ever store tokens in it. I still think it would be easier and better to implement a custom Properties class instead of a custom Storage class, but I also think adding a `setStoage()` method would be fine if you want to send a PR.

**Comment by erickoledadevrel** [comment]
Closing this FR, as it's an uncommon use case and I think the custom `Properties` class is an easier workaround for most people.

**Comment by Blacksmoke16** [comment]
@erickoledadevrel After thinking for quite a while, a question I came up with is:

> Assuming you're in a standard OAuth2 flow, what's the benefit of using _BOTH_ `Properties` and a `Cache`? 

The [current limitations](https://developers.google.com/apps-script/guides/services/quotas#current_limitations) of 500kb of total storage in `Properties` is the crux of the issue here as as you auth more characters you'd eventually hit that limit. However, given these tokens expire in 20min anyway, wouldn't it just be sufficient to solely rely on a document cache which have much more manageable limits (250 char keys, and 100KB per key). I'm still storing the static data in document properties such that the OAuth service is able to know what cache key to use, but that's tiny comparatively.

Do you have any thoughts on this? And related, do you think it makes sense to be able to customize the cache server expiry? 6 hours is a bit high but not the end of the world as it would see its expired and override it anyway.
